//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TP_DeviceTypeXStatus
    {
        [Key]
        public int deviceType { get; set; }
        public int statusId { get; set; }
    
        public virtual TP_DeviceStatus TP_DeviceStatus { get; set; }
        public virtual TP_DeviceType TP_DeviceType { get; set; }
    }
}
