//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TP_Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TP_Device()
        {
            this.TX_Event_History = new HashSet<TX_Event_History>();
        }
        [Key]
        public long deviceId { get; set; }
        public int stationId { get; set; }
        public int deviceType { get; set; }
        public long deviceSerialNo { get; set; }
        public string deviceNo { get; set; }
        public int deviceState { get; set; }
        public bool isInUse { get; set; }
        public System.DateTime createDate { get; set; }
    
        public virtual TP_DeviceType TP_DeviceType { get; set; }
        public virtual TP_Station TP_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_Event_History> TX_Event_History { get; set; }
    }
}
