//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TP_Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TP_Events()
        {
            this.TX_Event_History = new HashSet<TX_Event_History>();
            this.TP_DeviceType = new HashSet<TP_DeviceType>();
        }
        [Key]
        public int eventId { get; set; }
        public int eventType { get; set; }
        public string eventDescription { get; set; }
        public int eventSeverity { get; set; }
        public int colorSeverity { get; set; }
        public bool isInUse { get; set; }
        public System.DateTime createDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_Event_History> TX_Event_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TP_DeviceType> TP_DeviceType { get; set; }
    }
}
